---
title: "Modelling recipes"
knit: (function(input_file, encoding) {out_dir <- 'docs';rmarkdown::render(input_file,encoding=encoding, output_file=file.path(dirname(input_file), out_dir,'index.html'))})
subtitle: "With (life) insurance data"
author: "[Pat Reen](https://www.linkedin.com/in/patrick-reen/)"
output: 
  rmdformats::downcute:
    includes: 
        in_header: docs\header.html
    self_contained: false
    code_folding: hide
link-citations: yes
---

```{r Site, echo=FALSE}

# Create the external file

FileText <- paste0('
name: "More-Modelling-Recipes"
navbar:
  title: "More-Modelling-Recipes"
  left:
    - text: "Home"
      href: index.html
    - text: "Other"
      href: other.html
')

readr::write_lines(FileText, file = "docs/_site.yml")
```

```{r htmlHeader, echo=FALSE}
# Create the external file

FileText<- paste0('

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add icon font -->
<p style="position:absolute; top:0; right:20px; ">
    <a href="https://www.linkedin.com/in/patrick-reen/" class="fa fa-linkedin" style="font-size:24px"></a>
    <a href="https://github.com/Pat-Reen/" class="fa fa-github" style="font-size:24px"></a>
</p>

')

readr::write_lines(FileText, file = "docs/header.html")
```

```{r htmlOther, echo=FALSE}
# Create the external file

FileText<- paste0('

---
title: "About This Website"
---

More about this website.

')

readr::write_lines(FileText, file = "docs/other.html")
```

# Overview {.tabset .tabset-fade .tabset-pills}
## Background 
This document sets out a few practical recipes for modelling with (life) insurance data.